site/core/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import pmonitor.urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    #monitor app is going to be main page
    #news app on news/
    url(r'^pipeline/', include('pmonitor.urls', namespace='pmonitor')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
]

site/news/urls.py
from django.conf.urls import patterns, url
from news import views

urlpatterns = patterns('',
                       url(r'^$',
                           views.index, name='index'),
                       url(r'^about$',
                           views.about, name='about'),
                       url(r'^category/(?P<thiscategory>\w{0,50})/$',
                           views.category, name='category'),
                       url(r'^newspaper/(?P<newspaperlink>\w{0,50})/$',
                           views.newspaper, name='newspaper'),
                       url(r'^newspaper/(?P<newspaperlink>\w{0,50})/category/(?P<thiscategory>\w{0,50})/$',
                           views.newspaper_category, name='newspaper_category'),
                       url(r'^filterfeeds$',
                           views.filterfeeds, name='filterfeeds'),
                       url(r'^userfeeds$',
                           views.userfeeds, name='userfeeds'),
                       url(r'^add_to_bookmark/(?P<article_id>[0-9]+)$',
                           views.add_to_bookmark, name='add_to_bookmark'),
                       url(r'^remove_from_bookmark/(?P<article_id>[0-9]+)$',
                           views.remove_from_bookmark, name='remove_from_bookmark'),
                       url(r'^bookmark$',
                           views.bookmark, name='bookmark'),
                       url(r'^images/(?P<urlid>[0-9]+)$',
                           views.image_text, name='image_text'),
                       url(r'^allimages$',
                           views.allarticles, name='allarticles'),
                       url(r'^login/$',
                           views.user_login, name='user_login'),
                       url(r'^process_login$',
                           views.process_login, name='process_login'),
                       url(r'^logout/$',
                           views.user_logout, name='user_logout'),
                       url(r'^register$',
                           views.register, name='register'),
                       url(r'^process_register$',
                           views.process_register, name='process_register'),
                       url(r'^reset_password$',
                           views.reset_password, name='reset_password'),
                       url(r'^change_password$',
                           views.change_password, name='change_password'),
                       url(r'^search_keyword$',
                           views.search_keyword, name='search_keyword'),
                       url(r'^article_by_keyword$',
                           views.article_by_keyword, name='article_by_keyword'),
                      )

site/news/models.py
from django.db import models
from datetime import datetime


class  RSSurl(models.Model):
    #rss
    rss_url = models.URLField()
    valid = models.BooleanField()


#in order to create urls, newspaper and categories can be slugified
class Article(models.Model):
    """
    Model to store all the article data coming from the RSS feeds
    obtained through feedparser
    """
    # rssurl_id | Newspaper | Category | Title | Link | Description
    rssurl_id = models.IntegerField(default=0)
    newspaper = models.CharField(max_length=20) 
    category = models.CharField(max_length=15)
    title = models.TextField(default='')
    url = models.URLField()
    description = models.TextField(default='')
    publish_date = models.DateTimeField(default=datetime.now)
    
    def __unicode__(self):
        return self.title

class Image(models.Model):
    """
    Image model to grab image from a particular url and attach it to an article in the db
    will store image source and main article text
    """
    # article_id | images_url
    article_id = models.IntegerField()
    image_url = models.URLField()
    main_text = models.TextField(null=True, blank=True)

class Bookmark(models.Model):
    """
    Bookmark model to store saved articles based on user id
    """
    # user_id | article_id
    user_id = models.IntegerField()
    article_id = models.IntegerField()

site/news/views.py
'''
views file to render pages
'''
import re
import feedparser
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from news.models import Article, Image, Bookmark

newspapers = {'nytimes': 'New York Times', 'latimes': 'Los Angeles Times',
              'miamiherald': 'Miami Herald', 'seattletimes':'Seattle Times',
              'chron':'Houston Chronicles', 'denverpost':'Denver Post'}

#User Management Views
def user_login(request):
    """Renders The Login page"""
    template = 'login.html'
    return render(request, template)

def process_login(request):
    """Process the Login Form to login the user"""
    email = request.POST['email']
    password = request.POST['password']

    # Validation
    required_fields = [email, password]
    trimmed = [i.strip() for i in required_fields]
    if "" in trimmed:
        return render(request, 'login.html', {'email': email, 'message': 'Missing Required Fields'})

    # Email validation
    if not re.match(r"[^@]+@[^@]+\.[^@]+", email):
        return render(request, 'login.html', {'email': email, 'message': 'Invalid Email'})

    user = authenticate(username=email, password=password)

    if user is not None:
        login(request, user)
        previous_page = request.GET['next']
        if previous_page == '/news/register':
            return redirect('news:index')
        elif previous_page == "":
            return redirect('news:index')
        else:
            return redirect(previous_page)

    return render(request, 'index.html')

def user_logout(request):
    """Logout the user"""
    logout(request)
    return redirect(request.GET['next'])

def register(request):
    """Renders the Register page"""
    template = 'register.html'
    return render(request, template)

def process_register(request):
    """Process the Register Form to create a user"""
    first_name = request.POST['first_name']
    last_name = request.POST['last_name']
    email = request.POST['email']
    password = request.POST['password']
    confirm_password = request.POST['confirm_password']

    # Validation
    required_fields = [email, first_name, last_name, password, confirm_password]
    trimmed = [i.strip() for i in required_fields]
    if "" in trimmed:
        return render(request, 'register.html', {
            'first_name': first_name,
            'last_name': last_name,
            'email': email,
            'message': 'Missing Required Fields'})

    # Password matching
    if password != confirm_password:
        return render(request, 'register.html', {
            'first_name': first_name,
            'last_name': last_name,
            'email': email,
            'message': 'Non-matching Passwords'})

    # Email validation
    if not re.match(r"[^@]+@[^@]+\.[^@]+", email):
        return render(request, 'register.html', {
            'first_name': first_name,
            'last_name': last_name,
            'email': email,
            'message': 'Invalid Email'})

    user = User.objects.create_user(email, email, password)
    user.first_name = first_name
    user.last_name = last_name
    user.save()

    return redirect('news:user_login')

def reset_password(request):
    """Renders the Reset Password page"""
    template = 'reset_password.html'
    return render(request, template)

def change_password(request):
    """Process the reset_password Form to reset the user's password"""
    email = request.POST['email']
    old_password = request.POST['old_password']
    new_password = request.POST['new_password']
    confirm_password = request.POST['confirm_password']

    # Validation
    required_fields = [email, old_password, new_password, confirm_password]
    trimmed = [i.strip() for i in required_fields]
    if "" in trimmed:
        return render(request, 'reset_password.html', {
            'email': email,
            'message': 'Missing Required Fields'})

    # Password matching
    if new_password != confirm_password:
        return render(request, 'reset_password.html', {
            'email': email,
            'message': 'New Password is different from Confirm Password'})

    # Email validation
    if not re.match(r"[^@]+@[^@]+\.[^@]+", email):
        return render(request, 'reset_password.html', {
            'email': email,
            'message': 'Invalid Email'})

    user = authenticate(username=email, password=old_password)

    if user is not None:
        login(request, user)
        userget = User.get(username=email)
        userget.set_password(new_password)
        userget.save()
        logout(request)
        return redirect('news:user_login')
    else:
        return render(request, 'reset_password.html', {
            'email': email,
            'message': 'Incorrect Password to Email or Email does not exist'})

def index(request):
    """Renders the Index Page (Main Page)"""
    template = 'index.html'
    query = Article.objects.values_list('category').distinct()
    dictcategory = []
    article_has_image = []
    num = 5 #Number of Titles to display on Category blocks
    for categorys in query:
        categorys = categorys[0].encode('utf-8')
        feeds = Article.objects.filter(category=categorys).order_by('-publish_date')[:num]

        #find out if each article in feed has image and text in Image table
        for each in feeds:
            article = Image.objects.filter(article_id=each.id)
            if len(article) > 0:
                article_has_image.append(each.id)

        dictcategory.append({
            "category" : categorys,
            "feeds" : feeds
            })

    nums = 5
    query = Article.objects.values_list('newspaper').distinct()
    dictpaper = []
    for newspaper in query:
        newspaper = newspaper[0].encode('utf-8')
        link = [key for key, value in newspapers.iteritems() if value == newspaper][0]

        #find out if each article in feed has image and text in Image table
        for each in Article.objects.filter(newspaper=newspaper)[:nums]:
            article = Image.objects.filter(article_id=each.id)
            if len(article) > 0:
                article_has_image.append(each.id)

        dictpaper.append({
            "newspaperlink": link,
            "newspaper" : newspaper,
            "title" : Article.objects.filter(newspaper=newspaper).order_by('-publish_date')[:nums]
            })

    bookmarks = []
    for each in Bookmark.objects.filter(user_id=request.user.id):
        bookmarks.append(each.article_id)

    return render(request, template, {
        'dictcategory' : dictcategory,
        'dictpaper' : dictpaper,
        'bookmarks': bookmarks,
        'article_has_image':article_has_image,
        'n':num})

def about(request):
    '''About page'''
    return render(request, 'about.html')

def filterfeeds(request):
    """Renders the FilterFeeds Page"""
    template = 'filterfeeds.html'
    query = Article.objects.values_list('newspaper').distinct()
    dictcheckbox = []
    for newspaper in query:
        newspaper = newspaper[0].encode('utf-8')
        category = Article.objects.filter(newspaper=newspaper).values_list('category').distinct()

        dictcheckbox.append({
            "title" : newspaper,
            "category" : [x[0].encode('utf-8') for x in category]
        })

    return render(request, template, {'dictcheckbox': dictcheckbox})

def userfeeds(request):
    """Process the FilterFeeds Form to renders the Userfeeds Page"""
    template = 'userfeeds.html'
    postlist = []
    for item in request.POST.getlist('newspapercategory[]'):
        postlist += [x.strip() for x in item.split(',')]
    dictuserfeeds = []
    num = 10

    for news, cat in zip(postlist[0::2], postlist[1::2]):
        feeds = Article.objects.filter(newspaper=news, category=cat).order_by('-publish_date')[:num]

        dictuserfeeds.append({
            "newspaper" : news,
            "category" : cat,
            "feeds" : feeds
            })

    dictuserinput = []
    for url in request.POST.getlist('userRSS[]'):
        if url != "":
            rss = feedparser.parse(url)
            titlelink = []
            size = len(rss.entries)
            for post in rss.entries[:num]:
                title = post.title.encode('utf-8')
                link = post.link
                titlelink.append({
                    "title" : title,
                    "url" : link
                    })
            dictuserinput.append({
                "rssurl" : url,
                "titlelink" : titlelink,
                "size" : size
                })

    return render(request, template, {
        'dictuserfeeds': dictuserfeeds,
        'dictuserinput': dictuserinput})

def newspaper(request, newspaperlink):
    """Renders the Newspaper Page for each Newspaper which display all the categories with a set amount of article titles"""
    template = 'newspaper.html'
    paper = newspapers[newspaperlink]
    query = Article.objects.filter(newspaper=paper).values_list('category').distinct()

    dictcategory = []
    article_has_image = []
    category_has_image = []
    for category in query:
        category = category[0].encode('utf-8')
        titles = Article.objects.filter(newspaper=paper, category=category)
        dictcategory.append({
            "size": len(titles),
            "category" : category,
            "title" : Article.objects.filter(newspaper=paper, category=category).order_by('-publish_date')
        })
        for each in titles:
            article = Image.objects.filter(article_id=each.id)
            if len(article) > 0:
                article_has_image.append(each.id)
                if category not in category_has_image:
                    category_has_image.append(category)

    bookmarkfilter = Bookmark.objects.filter(user_id=request.user.id)
    bookmark = []
    for each in bookmarkfilter:
        bookmark.append(each.article_id)

site/news/templates/about.html
{% extends 'base.html' %}

{% block title %} About {% endblock %}

{% block body_block %}

	<!--if you need to adjust css, do it through the style tag here-->
	<style>

	</style>

	<!--populates categories based on selected newspaper-->
    <div class="col-md-12">

        <div class="col-md-12">
            <div class="panel panel-primary" id="panels">
                <div class="panel-heading"><h1 style="text-align: center; height: 50px;">About News Aggregator</h1></div>
            </div>
        </div>
		
        <div class="col-md-6">
            <div class="panel panel-primary" id="panels" >

                <div class="panel-body" style="height: 300px;">
					<p>					
						What is this News Aggregator?</br>
						This news aggregator gathers articles from RSS links and displays them for you to view.
					</p>					

					<p>					
						Why and what for?</br>
						This News Aggregator is one of two parts of our Pipeline Monitor project. It is the process that we chose to monitor.	
					</p>

					<p>					
						How do I use it?</br>
						On the main page, you can see a plethora of articles. The articles come from either a category or a newspaper. If the title and description of the article are of interest to you, you can click on the title and it will lead you to the source of the article.
					</p>

					<p>					
						What else?</br>
						Additionally, you can also go to the 'Create you own feed' page and pick only categories or newspapers that you're interested in. You can also provido a RSS URL and it will get the articles for you.
					</p>


                </div>
                
            </div>
            
        </div>



    </div>

{% endblock %}

site/news/templates/allarticles.html
{% extends 'base.html' %}

{% block title %} All Articles {% endblock %}

{% block body_block %}
<style>
    
    img{
        width:32%;
        height:24%;
        float:left;
        left:5%;
    }



.article_main{
    margin-top:10px;
    display:block
    height:24%;
    overflow:scroll;
    
}

.imgdiv{
   }
.maintext{
    width: 65%;
    height:20%;
    margin-left:5%;
    overflow:scroll;
    padding-left:2%;
    

}

    </style>

	<div class="col-md-12">
        
		<div class="col-md-12">
			<div class="panel panel-primary" id="panels">
                {% if by_keyword %}
                <div class="col-md-12">
                    <div class="panel panel-primary" id="panels">
                        <div class="panel-heading"><h1 style="text-align: center;">{{num}} Articles found by your keywords: {{keyword}}</h1></div>
                    </div>
                </div>
                {% else %}
				<div class="panel-heading">
                    <h1 style="text-align: center;">Top Image and Main Text For &nbsp; {{num}} &nbsp; Articles</h1>
                </div>
                {% endif %}
			</div>
		</div>
        
        <div class="panel-body">
            <ul style="margin-left: -15px;">
                {% for each in article_main %}
                <div class="article_main">
                    
                    <li style="font-size:20px;">
                        &nbsp;{{each.newspaper}}&nbsp;|&nbsp;{{each.category}}&nbsp;| <a class="blackblue" href="{{each.url}}">{{each.title}}</a>
                    </li>
                    <div class="imgdiv">
                        <img src="{{each.image}}">
                    </div>
                    <div class='maintext'>
                        <p> {{each.text}}</p>
                    </div>
                </div>
                
                {% endfor %}
            </ul>
        </div>

</div>
{% endblock %}

site/news/templates/base.html
<!DOCTYPE html>

{% load bootstrap3 %}
{% bootstrap_css %}
{% load staticfiles %}

<html>
	<head>

		<link rel="stylesheet" type="text/css" href="{% static 'stylesheet/style.css' %}" />
		<link href='http://fonts.googleapis.com/css?family=Lobster+Two ' rel='stylesheet' type='text/css'>
		<title>
			News Aggregator | {% block title %} {% endblock %}
		</title>	
	</head>

	<body>

	<div class="row" style="margin-bottom: 20px;border-bottom: solid 1px lightgray;">

		<!--headers	-->
		<div class="col-md-12">

			<!--main header-->
			<div class="col-md-8">
				<h1>RSS FEEDS</h1>
			</div>

			<!--Login & Registration-->
			<div class="col-md-4">
				{% if user.is_authenticated %}
				<a href="{% url 'news:user_logout' %}?next={{request.path}}"><button type="button" class="btn btn-lg btn-info" style="float: right; padding:0px; height: 25px; width: 100px">Logout</button></a>
				{% else %}				
				<a href="{% url 'news:register' %}"><button type="button" class="btn btn-lg btn-info" style="float: right; padding:0px; height: 25px; width: 100px">Register</button></a>
				<a href="{% url 'news:user_login' %}?next={{request.path}}"><button type="button" class="btn btn-lg btn-info" style="float: right; margin-right: 5px; padding:0px; height: 25px; width: 100px">Login</button></a>
				{% endif %}
			</div>

		</div>
		
		<!--nav bar-->
		<div class="col-md-12" style="margin-bottom: 20px;border-bottom: solid 1px lightgray;">
			<div class="col-md-12 nav_bar">
				<ul class="nav nav-pills">
					<!--Home | See pipeline | Create own feed | Bookmark | All Images | About-->
					<li>
						<a href="{% url 'news:index' %}">Home</a>
					</li>
					<li>
						<a href="{% url 'pmonitor:index' %}">See pipeline</a>
					</li>
                    <li>
                    <a href="{% url 'dashboard:index' %}">Dashboard </a>
                    </li>
					<li>
						<a href="{% url 'news:filterfeeds' %}">Create own Feed</a>
					</li>
					{% if user.is_authenticated %}
					<li>
						<a href="{% url 'news:bookmark' %}">Bookmarked Feeds</a>
					</li>
					{% endif %}
					<li>
						<a href="{% url 'news:allarticles' %}">All Articles</a>
					</li>
                    <li>
                        <a href="{% url 'news:search_keyword' %}">Search By Keyword</a>
                    </li>
					<li>
						<a href={% url 'news:about' %}>About</a>
					</li>
				</ul>
			</div>
		</div>
		

		<!--enter content here-->
		{% block body_block %}

		{% endblock %}	

	
	<!--close first div-->
	</div>

	</body>

	<!--JS here-->
	<script type="text/javascript" src="{% static 'javascript/script.js' %}"></script>
{% if message %}
	<script type="text/javascript">
    	alert('{{ message }}');
	</script>
{% endif %}

</html>

{% bootstrap_javascript %}

site/news/templates/bookmark.html
{% extends 'base.html' %}

{% block title %} Bookmark {% endblock %}

{% block body_block %}

	<div class="col-md-12">

		<!--header-->
		<div class="col-md-12">
			<div class="panel panel-primary" id="panels">
				<div class="panel-heading"><h1 style="text-align: center;">Bookmarked Feeds</h1></div>
			</div>
		</div>

		{% for key,value in bookmarkdict.items %}
		<div class="col-md-4">
			<div class="panel panel-primary" id="panels">

				<div class="panel-heading" style="height:40px">
					<a class="blackblue" href="#">{{key}}</a>
				</div>

				<p class="panel-body" style="margin-top: -20px;">
					<ol style="overflow: hidden;margin-left: -15px">
					{% for each in value %}
						<li style="font-size:12px;font-weight: bold;height: 20px;white-space: nowrap;"><a class="blackblue" href="{{each.url}}">{{each.title}}</a></li>

						<!--unbookmark-->
						{% if user.is_authenticated %}
                            <a href="{% url 'news:remove_from_bookmark' each.id %}?next={{request.path}}"> UnBookmark </a>
						{% endif %}									
					{% endfor %}
					</ol>
				</p>

			</div>
		</div>
		{% endfor %}
	</div>

{% endblock %}

site/news/templates/category.html
{% extends 'base.html' %}

{% block title %} {{catename}} {% endblock %}

{% block body_block %}
	
	<!--if you need to adjust css, do it through the style tag here-->
	<style>
        .col-md-6{
             display: inline-block;
            width: 60%;
            left: 20%;
            
        }
	</style>
    
	<!--populates categories based on selected newspaper-->
    <div class="col-md-12">

        <div class="col-md-12">
            <div class="panel panel-primary" id="panels">
                <div class="panel-heading"><h1 style="text-align: center;">Newspaper Category</h1></div>
            </div>
        </div>
        
        <div class="col-md-6">
            <div class="panel panel-primary" id="panels" >
                <div class="panel-heading">
                    <h3 style="text-align: center;">{{catename}}</h3>
                </div>
            
            <div class="panel-body" style="height: 600px; overflow: scroll;">
                <p  style="margin-top: -20px;">
                <ul style="margin-left: -15px;">
                    {% for each in category %}
                    <li><b><a class="blackblue" href="{{each.url}}">{{each.title}}</a></b></li>
                    <p>--{{each.description}}</p>
                    {% endfor %}
                </ul>
                </p>
            
            </div>
        <div class="panel-footer">Number of feeds: {{size}}</div>
        </div>
        
   </div>


{% endblock %}

site/news/templates/filterfeeds.html
{% extends 'base.html' %}

{% block title %} Create Feed {% endblock %}

{% block body_block %}

	<div class="col-md-12">

		<!--header-->
		<div class="col-md-12">
			<div class="panel panel-primary" id="panels">
				<div class="panel-heading"><h1 style="text-align: center;">Filter Feeds</h1></div>
			</div>
		</div>

		<!--checkboxes for each paper-->
		<form name="myForm" action="userfeeds" method="post">

		{% csrf_token %}
		{% for newspaper in dictcheckbox %}
		<div class="col-md-4">
			<div class="panel panel-primary" id="panels">
				<div class="panel-heading" style="height:40px">
					<a href="">{{newspaper.title}}</a>
				</div>

				<p class="panel-body" style="height:150px">
					{% for each in newspaper.category %}
						<input type="checkbox" name="newspapercategory[]" value="{{newspaper.title}}, {{each}}">{{each}}<br>
					{% endfor %}
				</p>
			</div>
		</div>
		{% endfor %}

		<!--last box has user input-->
		<div class="col-md-4">
			<div class="panel panel-primary" id="panels">
				
				<div class="panel-heading">
					Add your own RSS Feeds
				</div>

				<p class="panel-body" style="margin-top:-30px;margin-left: 100px;">
					<div id="UserRssInput" style="margin-left: 10px;">
						<input type="text" id="userRSS" name="userRSS[]">
					</div>						
				</p>

				<div class="panel-footer">
					<input type="button" id="addInputField" class="btn btn-primary" value="Add RSS">
                    <input type="button" id="deleteInputField" class="btn btn-primary" value="Delete Last RSS">
					<input type="submit" id='filter_button' value="Filter" class="btn btn-primary">
				</div>
			</div>
		</form>
        
        
		
	<!--closes last div-->
	</div> 

{% endblock %}

site/news/templates/index.html
{% extends 'base.html' %}

{% block title %} Main {% endblock %}

{% block body_block %}

	<!--populates category boxes - 6-->
	<div class="col-md-8">
		<div class="col-md-12">
			<div class="panel panel-primary" id="panels">
				<div class="panel-heading"><h1 style="text-align: center;">Newspaper Categories</h1></div>
			</div>
		</div>

		{% for category in dictcategory %}
		<div class="col-md-12">
			<div class="panel panel-primary" id="panels">
				<div class="panel-heading" style="height:40px; text-align: center; font-size: 20px;">
					<a href="/news/category/{{category.category}}">{{category.category}}</a>
				</div>

				<p class="panel-body" style="margin-top: -20px;">

				<ol style="overflow: hidden;margin-left: -15px">
					{% for each in category.feeds %}

						<!--title with description below-->
						<li style="font-size:15px;font-weight: bold;height: 20px;white-space: nowrap;"><a class="blackblue" href="{{each.url}}">{{each.title}}</a></li>

						-- {{each.description}} </br>

                        {% if each.id in article_has_image %}
                        <a href="/news/images/{{each.id}}"> View Top Image and Main Text</a> | 
                        {% endif %}

                         <!--Bookmark-->
						{% if user.is_authenticated %}
							{% if each.id in bookmark %}
                                <a href="{% url 'news:remove_from_bookmark' each.id %}?next={{request.path}}"> UnBookmark </a>
							{% else %}
								<a href="{% url 'news:add_to_bookmark' each.id %}?next={{request.path}}"> Bookmark </a>
							{% endif %}
						{% endif %}			
					{% endfor %}
				</ol>
				</p>
                <div class="panel-footer">Number of Feeds: {{n}} </div>
			</div>
		</div>
		{% endfor %}
	</div>

	<!--populate right side bar - stories from other papers-->
	<div class="col-md-4" style="margin-bottom: 15px;border-left: solid 1px lightgray;">
		<ul>
			<h2>Stories in Other Newspapers</h2>		
		</ul>
		{% for paper in dictpaper %}
		<ul>
			<a class="blackblue" href="/news/newspaper/{{paper.newspaperlink}}" style="text-decoration: underline"><h3>{{paper.newspaper}}</h3></a>
			{% for each in paper.title %}
			<li><a class="blackblue" href="{{each.url}}">{{each}}</a></li>
            {% if each.id in article_has_image %}
			<a href="/news/images/{{each.id}}"> View Top Image and Main Text</a> | 
            {% endif %}
            
                <!--Bookmark-->
				{% if user.is_authenticated %}
					{% if each.id in bookmark %}
                        <a href="{% url 'news:remove_from_bookmark' each.id %}?next={{request.path}}"> UnBookmark </a>
					{% else %}
						<a href="{% url 'news:add_to_bookmark' each.id %}?next={{request.path}}"> Bookmark </a>
					{% endif %}
				{% endif %}			
			{% endfor %}
		</ul>
		{% endfor %}		
	</div>

{% endblock %}

site/news/templates/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}

{% block body_block %}

	<div class="container" style="width:500px">
		<div class="row">
			<div class="col-md-12">
				<h1>Login</h1>

				<form action="{% url 'news:process_login' %}?next={{request.GET.next}}" method="post">
				{% csrf_token %}
					<div class="form-group">						
						<label>Email</label>
						<input type="email" name="email" class="form-control" placeholder="Enter email" value="{{email}}">
					</div>
					<div class="form-group">
						<label>Password</label>
						<input type="password" name="password" class="form-control" placeholder="Password">
					</div>
					<button type="submit" class="btn btn-primary">Submit</button>
					<a class="btn btn-default" href="{% url 'news:register' %}" role="button">Register</a>
				</form>
                <a href="{% url 'news:reset_password' %}">Reset Password</a>
			</div>
		</div>
	</div>
{% endblock %}

site/news/templates/register.html
{% extends 'base.html' %}

{% block title %} Register {% endblock %}

{% block body_block %}
    <style>
        .login {
            width: 500px;
        }
        .flash {
            width: 500px;
            margin: 0 auto;
        }
    </style>

    <div class="container login">
		<div class="row">
			<div class="col-md-12">
				<h1>Register</h1>

				<form action="{% url 'news:process_register' %}" method="post">
				{% csrf_token %}
                    <div class="form-group">
						<label>First Name</label>
						<input type="text" name="first_name" class="form-control" placeholder="Enter first name" value="{{first_name}}">
					</div>
                    <div class="form-group">
						<label>Last Name</label>
						<input type="text" name="last_name" class="form-control" placeholder="Enter last name" value="{{last_name}}">
					</div>
					<div class="form-group">
						<label>Email</label>
						<input type="email" name="email" class="form-control" placeholder="Enter email" value="{{email}}">
					</div>
					<div class="form-group">
						<label>Password</label>
						<input type="password" name="password" class="form-control" placeholder="Password">
					</div>
                    <div class="form-group">
						<label>Confirm Password</label>
						<input type="password" name="confirm_password" class="form-control" placeholder="Confirm password">
					</div>
					<button type="submit" class="btn btn-primary">Submit</button>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

site/news/templates/search_keyword.html
{% extends 'base.html' %}

{% block title %} Create Feed {% endblock %}

{% block body_block %}

	<div class="col-md-12">

		<!--header-->
		<div class="col-md-12">
			<div class="panel panel-primary" id="panels">
				<div class="panel-heading"><h1 style="text-align: center;">Search Articles by keyword</h1></div>
			</div>
		</div>

		<!--checkboxes for each paper-->
		<form name="myForm" action="article_by_keyword" method="post">

		{% csrf_token %}

		<!--last box has user input-->
		<div class="col-md-4">
			<div class="panel panel-primary" id="panels">
				
				<div class="panel-heading">
					Input your keyword
				</div>

				<p class="panel-body" style="margin-top:-30px;margin-left: 100px;">
					<div id="UserRssInput" style="margin-left: 10px;">
						<input type="text" name="userkeyword">
					</div>						
				</p>

				<div class="panel-footer">
					<input type="submit" value="Filter" class="btn btn-primary">
				</div>
			</div>
		</form>				
		
	<!--closes last div-->
	</div> 

{% endblock %}