site/core/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import pmonitor.urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    #monitor app is going to be main page
    #news app on news/
    url(r'^pipeline/', include('pmonitor.urls', namespace='pmonitor')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
]

site/dashboard/urls.py
from django.conf.urls import patterns, url
from dashboard import views

urlpatterns = patterns('',
                       url(r'^$',
                           views.index, name='index'),
                       url(r'^rssurl/(?P<rssurl_id>[0-9]+)$',views.rssurl,name='rssurl'),
                       url(r'^rss$',views.rss,name='rss'),
                        url(r'^articles$',views.articles,name='articles'),
                       url(r'^images$',views.images,name='images'),
                       url(r'^texts$',views.texts,name='texts'),
                       url(r'^downloadall$',views.downloadall,name='downloadall'),
                       url(r'^downloadrssCSV$',views.downloadrssCSV,name='downloadrssCSV'),
                       url(r'^downloadrssTXT$',views.downloadrssTXT,name='downloadrssTXT'),
                      )

site/news/urls.py
from django.conf.urls import patterns, url
from news import views

urlpatterns = patterns('',
                       url(r'^$',
                           views.index, name='index'),
                       url(r'^about$',
                           views.about, name='about'),
                       url(r'^category/(?P<thiscategory>\w{0,50})/$',
                           views.category, name='category'),
                       url(r'^newspaper/(?P<newspaperlink>\w{0,50})/$',
                           views.newspaper, name='newspaper'),
                       url(r'^newspaper/(?P<newspaperlink>\w{0,50})/category/(?P<thiscategory>\w{0,50})/$',
                           views.newspaper_category, name='newspaper_category'),
                       url(r'^filterfeeds$',
                           views.filterfeeds, name='filterfeeds'),
                       url(r'^userfeeds$',
                           views.userfeeds, name='userfeeds'),
                       url(r'^add_to_bookmark/(?P<article_id>[0-9]+)$',
                           views.add_to_bookmark, name='add_to_bookmark'),
                       url(r'^remove_from_bookmark/(?P<article_id>[0-9]+)$',
                           views.remove_from_bookmark, name='remove_from_bookmark'),
                       url(r'^bookmark$',
                           views.bookmark, name='bookmark'),
                       url(r'^images/(?P<urlid>[0-9]+)$',
                           views.image_text, name='image_text'),
                       url(r'^allimages$',
                           views.allarticles, name='allarticles'),
                       url(r'^login/$',
                           views.user_login, name='user_login'),
                       url(r'^process_login$',
                           views.process_login, name='process_login'),
                       url(r'^logout/$',
                           views.user_logout, name='user_logout'),
                       url(r'^register$',
                           views.register, name='register'),
                       url(r'^process_register$',
                           views.process_register, name='process_register'),
                       url(r'^reset_password$',
                           views.reset_password, name='reset_password'),
                       url(r'^change_password$',
                           views.change_password, name='change_password'),
                       url(r'^search_keyword$',
                           views.search_keyword, name='search_keyword'),
                       url(r'^article_by_keyword$',
                           views.article_by_keyword, name='article_by_keyword'),
                      )

site/dashboard/models.py
from django.db import models

# Create your models here.

site/dashboard/views.py
#!/usr/bin/python
# -*- coding: UTF-8  -*-
from django.shortcuts import render
from django.contrib import admin
from django.db import models
from news.models import Article, Image, RSSurl
import csv
from django.utils.encoding import smart_str, smart_unicode
from django.http import HttpResponse

# Create your views here.

'''index page of dashboard app, this page will show  the statistic of data populated to database,
    show the number of valid  and invalid rss urls, the number of feed populated from each rss url,
    the number of image from each rss url and the number of article with main text extraced, and display 
the percentage for analysis, each valid rss url can link to  the dashboard for the artciles populated from this rss url'''


def index(request):
    
    template = 'dash_index.html'
    #initialize
    feedurls=[]
    total_articles = 0
    total_images = 0
    total_text = 0
    pct_of_images = 0
    pct_of_text = 0
    
    #get the array of rss url from RSSurl and number of valid and invalid rssurl
    query = RSSurl.objects.all().distinct()
    num_urls = len(query)
    valid_query = RSSurl.objects.filter(valid=True)
    valid_urls = len(valid_query)
    
    if num_urls == 0:
        pct_valid = 0
    else:
        pct_valid = valid_urls/float(num_urls) *100

    invalid_urls = num_urls - valid_urls
    
    #loop through the arrary
    for each in query:
        url = each.rss_url.encode('UTF-8')
        valid = each.valid
        articlequery = Article.objects.filter(rssurl_id=each.id)
        #initialize
        number_of_articles = len(articlequery)
        number_of_images = 0
        number_of_text= 0
        pct_of_images = 0
        pct_of_text = 0
        newspaper = ""
        category = ""
        
        #get the artcles for this rss url
        for article in articlequery:
            newspaper = article.newspaper
            category = article.category
            image = Image.objects.filter(article_id=article.id)
            
            if image :
                # get the stat of image
               if image[0].image_url :
                  number_of_images += 1
               # get the stat of main_text
               if image[0].main_text :
                  number_of_text += 1
    
        #pct for each rss url
        if number_of_articles==0:
            pct_of_images = 0
            pct_of_text = 0
        else:
            pct_of_images = number_of_images/float(number_of_articles) *100
            pct_of_text = number_of_text/float(number_of_articles)
        
        total_articles += number_of_articles
        total_images += number_of_images
        total_text += number_of_text
        
        feedurls.append({
            "rssurl_id":each.id,
            "url": url,
            "valid": valid,
            "newspaper": newspaper,
            "category": category,
            "number_of_articles": number_of_articles,
            "number_of_images": number_of_images,
            "number_of_text" : number_of_text,
            "pct_of_images": round(pct_of_images,2),
            "pct_of_text": round(pct_of_images,2)
            })
    #calculate the total pct
    if total_articles==0:
       pct_total_images = 0
       pct_total_text = 0
       pct_articles = 0
    else:
       pct_total_images = total_images/float(total_articles) *100
       pct_total_text   = total_text/float(total_articles) *100
       pct_articles = total_articles/float(len(query)*10) * 100
    summary = {
           "num_urls": num_urls,
           "valid_urls": valid_urls,
           "invalid_urls": invalid_urls,
           "pct_valid": round(pct_valid,2),
           "total_articles": total_articles,
           "pct_articles": round(pct_articles,2),
           "total_images": total_images,
           "pct_total_images": round(pct_total_images,2),
           "total_text": total_text,
           "pct_total_text": round(pct_total_text,2),
           }
    request.session['summary'] = summary
    request.session['rss'] = feedurls

    return render(request,template,{'feedurls':feedurls,'summary':summary})


'''show all the rss urls in rss.html page'''
def rss(request):
    template = 'rss.html'
    rss = request.session['rss']
    summary = request.session['summary']
    return render(request,template,{'rss':rss,'summary':summary})

'''dispaly the table for the stats of the artciles populated from this rssurl, to view if every data is valid or not '''
def rssurl(request,rssurl_id):

    template = 'rssfeed.html'
    summary = request.session['summary']
    articles = []
    rssurl = RSSurl.objects.filter(id=rssurl_id)[0].rss_url.encode('UTF-8')
    newspaper = ""
    category = ""
    #ge the array of articles from the rss url in Article
    rssquery = Article.objects.filter(rssurl_id=rssurl_id)
    
    for each in rssquery:
        newspaper = each.newspaper.encode('UTF-8')
        category = each.category.encode('UTF-8')
        title = each.title
        url = each.url
        publish_date = each.publish_date
        description = each.description

         #initialize
        image = ""
        text = ""
        # get the image or text for this article from Image
        image_text = Image.objects.filter(article_id=each.id)
        if image_text:
           image = image_text[0].image_url.encode('UTF-8')
           text = image_text[0].main_text.encode('UTF-8')
           if len(text) > 500:
               text = text[0:500]+"..."
        #append info to articles
        articles.append({
            "article_id": each.id,
            "title": title,
            "url": url,
            "publish_date": publish_date,
            "description": description,
            "image": image,
            "text": text,
         })

    return render(request,template,{'articles':articles,'rssurl':rssurl,
                  'newspaper':newspaper,'category':category,'summary':summary})


'''this will read info for all aritlces'''
def articles(request):
    
    template = 'articles.html'
    summary = request.session['summary']
    articles = []
    validrssurl = RSSurl.objects.filter(valid=True)
  
    for rss in validrssurl:
        
        feeds = Article.objects.filter(rssurl_id=rss.id)
        
        for each in feeds:
            # get data from artilces: newspapaer | category | title |url| publish_date |despcriton
            newspaper = each.newspaper.encode('UTF-8')
            category = each.category.encode('UTF-8')
            title = each.title
            articleurl = each.url
            publish_date = each.publish_date
            description = each.description
            if description > 100:
               description = description[0:100]+"..."
            # get data from Image:  Image | Text
            image = ""
            text = ""
            image_text = Image.objects.filter(article_id=each.id)
            if image_text:
               image = image_text[0].image_url.encode('UTF-8')
               text = image_text[0].main_text.encode('UTF-8')
               if len(text) > 300:
                   text = text[0:300]+"..."
        
             #append info to articles
            articles.append({
                         "article_id":each.id,
                         "newspaper": newspaper,
                         "category": category,
                         "title": title,
                         "article_url": articleurl,
                         "publish_date": publish_date,
                         "description": description,
                         "image": image,
                         "text": text,
                                    })

    return render(request,template,{'articles':articles,'summary':summary})


'''download save all data to csv file'''
    
def downloadall(request):
    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="DataPopulationResults.csv"'
    
    writer = csv.writer(response)
    writer.writerow(['Number', 'RSS url', 'Valid','Newspaper', 'Category','Title','Article URL','Publish Date', 'Description','Image URL','Main Text'])
    rssurl = RSSurl.objects.all().distinct()
    number = 0
    for rss in rssurl:
        
        feeds = Article.objects.filter(rssurl_id=rss.id)
        
        for each in feeds:
            number += 1
            # get data from artilces: newspapaer | category | title |url| publish_date |despcriton
            newspaper = smart_str(each.newspaper)
            category = smart_str(each.category)
            title = smart_str(each.title)
            articleurl = smart_str(each.url)
            publish_date = smart_str(each.publish_date)
            description = smart_str(each.description)
            # get data from Image:  Image | Text
            image_url = ""
            clean_text = ""
            image_text = Image.objects.filter(article_id=each.id)
            if image_text:
                image_url = image_text[0].image_url
                clean_text = smart_str(image_text[0].main_text)

        writer.writerow([number, rss.rss_url,rss.valid,newspaper,category,title,articleurl,publish_date,description,image_url,clean_text])
    
    return response

''' down the rss url in dababase as csv file'''
def downloadrssCSV(request):
    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="rssurl.csv"'

    writer = csv.writer(response)
    writer.writerow(['Number', 'RSS url'])
    rssurl = RSSurl.objects.all().distinct()
    number = 0
    for rss in rssurl:
        number += 1
        writer.writerow([number,rss.rss_url.encode('UTF-8')])
    
    return response
    
''' down the rss url in dababase as text file'''
def downloadrssTXT(request):
    # Create the HttpResponse object with the appropriate CSV header.

site/dashboard/templates/articles.html
{% extends 'dash_base.html' %}

{% block title %} Dashboard{% endblock %}

{% block body_block %}
<style>
    

a{
 word-wrap:break-word;
}

img{
    max-width: 100%;
    height: auto;
    width: auto;
}

</style>

        <!-- table head  -->
       <div class="row" style="width:100%;" >
           <div class="col-lg-8" style="width:100%;">
               <div class="panel panel-default" style="width:100%;">
                   <!-- /.panel -->
                   <div class="panel panel-default" style="width:100%;">
                       <div class="panel-heading" style="width:100%;">
                         <i class="fa fa-file-text-o fa-2x"> </i> &nbsp;<strong>All Articles</strong>
                       </div>
                       
                       
                       <!-- /.panel-heading -->
                       <div class="panel-body" style="width:100%;">
                           <div class="row" style="width:100%;">
                               <div class="col-lg-4" style="width:100%;">
                                   <div class="table-responsive" style="width:100%;">
   
   
      
      <!-- table -->
      <div class="panel-body" style="width:100%;">
          <div class="row" style="width:100%;">
              <div class="col-lg-4" style="width:100%;">
                  <div class="table-responsive" style="width:100%;overflow:scroll;height: 1000px">
                      <table class="table table-bordered table-hover table-striped" style="width:auto%; height: 100 %; overflow:scroll;text-align:center;">
                          <thead>
                <tr class="tablehead" style="text-align:center;" >
                    <th style="width:5%;;text-align:center;"><i class="fa fa-download fa-2x" style="color:#ff0066;"></th>
                    <th style="width:15%;text-align:center;" > Articles</th>
                    <th style="width:5%;text-align:center;"> Newspaper </th>
                    <th style="width:5%;text-align:center;"> Category </th>
                    <th style="width:5%;text-align:center;"> Published Date</th>
                    <th style="width:20%;text-align:center;"> Description </th>
                    <th style="width:15%;text-align:center;"> Image</th>
                    <th style="width:30%;text-align:center;">Main Text</th>
                </tr>
                {% for each in articles %}
                <tr class="tablerow">
                    <div class="tablerow">
                        <td><a>{{each.article_id}}</a></td>
                        <td><a href="{{each.url}}">{{each.title}}</a></td>
                        <td >{{each.newspaper}}</th>
                        <td > {{each.category}} </th>
                        <td > {{each.publish_date}}</td>
                        <td>{{each.description}}</td>
                        {% if each.image %}
                        <td class="image"><a href="{{each.image}}"><img src="{{each.image}}" ></a></td>
                        {% else %}
                        <td class="image"><i class="fa fa-frown-o  fa-2x" style="color:#666699;"></i></td>
                        {%endif%}
                        {% if each.image %}
                        <td>{{each.text}}</td>
                        {% else %}
                        <td><i class="fa fa fa-minus-square-o fa-2x" style="color:red;"></i></td>
                        {%endif%}
                    </div>
                </tr>
              {% endfor %}
            
            </table>
                  </div>
                  <!-- /.table-responsive -->
              </div>
              <!-- /.col-lg-4 (nested) -->
              <div class="col-lg-8">
                  <div id="morris-bar-chart"></div>
              </div>
              <!-- /.col-lg-8 (nested) -->
          </div>
          <!-- /.row -->
      </div>
      <!-- /.panel-body -->
</div>
 <!-- /.panel -->
                                   
</div>
<!-- /#wrapper -->








{% endblock %}

site/dashboard/templates/dash_base.html
<!DOCTYPE html>

{% load bootstrap3 %}
{% bootstrap_css %}
{% load staticfiles %}

<html>
    <head>
        
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
                            
        <title>RSS Feeds Dashboard</title>
        
        <link rel="stylesheet" type="text/css" href="{% static 'stylesheet/style.css' %}" />
                            <!-- Bootstrap Core CSS -->
         <link href="{% static 'dashboard/bower_components/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
                                
                                <!-- MetisMenu CSS -->
        <link href="{% static 'dashboard/bower_components/metisMenu/dist/metisMenu.min.css' %}" rel="stylesheet">
                                    
                                    <!-- Timeline CSS -->
         <link href="{% static 'dashboard/dist/css/timeline.css' %}" rel="stylesheet">
                                        
                                        <!-- Custom CSS -->
         <link href="{% static 'dashboard/dist/css/sb-admin-2.css' %}" rel="stylesheet">
             
                                            <!-- Morris Charts CSS -->
         <link href="{% static 'dashboard/bower_components/morrisjs/morris.css' %}" rel="stylesheet">
                                                
                                                <!-- Custom Fonts -->
         <link href="{% static 'dashboard/bower_components/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
                                                    
         <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
          <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
          <!--[if lt IE 9]>
         <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
           <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
           <![endif]-->
                                                    
    </head>

	<body>

	<div class="row" style="margin-bottom: 20px;border-bottom: solid 1px lightgray;">
    
    </div>

<div id="wrapper">
    
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'news:index'%}"> &nbsp; News <i class="fa fa-newspaper-o"></i></a>
        </div>
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'pmonitor:index' %}"> See Pipeline <i class="fa fa-desktop"></i></a>
        </div>
        <div class="navbar-header">
            <a class="navbar-brand" href={% url 'news:about' %}>About </a>
        </div>
               <!-- /.navbar-top-links -->
        
        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="sidebar-search">
                        <div class="input-group custom-search-form">
                            <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                                </div>
                        <!-- /input-group -->
                    </li>
                    <li>
                        <a href="{% url 'dashboard:index' %}"><i class="fa fa-dashboard fa-fw fa-2x"></i> RSS Feed Dashboard</a>
                    </li>
                    <li>
                        <a href="/dashboard/rss"><i class="fa fa-link fa-2x"></i> &nbsp;&nbsp;All RSS URLs </a>
                    </li>
                    <li>
                        <a href="/dashboard/articles"><i class="fa fa-newspaper-o fa-fw fa-2x"></i> All News Feeds</a>
                    </li>
                    <li>
                        <a href="/dashboard/images"><i class="fa fa-picture-o fa-fw fa-2x"></i> All Main Images </a>
                    </li>
                    <li>
                        <a href="/dashboard/texts"><i class="fa fa-file-text-o fa-fw fa-2x"></i> All Plain Texts </a>
                    </li>
                        </ul>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
    </nav>
</div>
<div id="wrapper">
    <!-- head -->
    <div id="page-wrapper" >
        <div class="row" >
            <div class="col-lg-12" style="background-color: lightgrey">
                <h1 class="page-header">RSS Feeds Data Population Analysis &nbsp;&nbsp;<i class="fa fa-line-chart fa-lg"></i></h1>
            </div>
            <!--  -->
        </div>
        <br>
<!-- 4 data boxes -->
<div class="row">
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa  fa-external-link fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge"> {{summary.num_urls}}</div>
                        <div class="huge"> {{summary.pct_valid}}%</div>
                        <div>Number of RSS URL </div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left"><a href="/dashboard/rss">View Details</a></span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-green">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-newspaper-o fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">{{summary.total_articles}}</div>
                        <div class="huge"> {{summary.pct_articles}}%</div>
                        <div class="huge"> </div>
                        <div>Number of Feeds</div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left"><a href="/dashboard/articles">View Details</a></span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-yellow">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-picture-o fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">{{summary.total_images}}</div>
                        <div class="huge">{{summary.pct_total_images}}%</div>
                        <div>Number of Images </div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left"><a href="/dashboard/images">View Details</a></span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-red" >
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-file-text-o fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">{{summary.total_text}}</div>
                        <div class="huge">{{summary.pct_total_text}}%</div>
                        <div>Number of Texts</div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left"><a href="/dashboard/texts">View Details</a></span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    
	</body>
    
    <!--enter content here-->
    {% block body_block %}
    
    {% endblock %}

	<!--JS here-->
    <!-- jQuery -->
    <script src="{% static 'dashboard/bower_components/jquery/dist/jquery.min.js' %}"></script>
    
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'dashboard/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    
    <!-- Metis Menu Plugin JavaScript -->
    <script src="{% static 'dashboard/bower_components/metisMenu/dist/metisMenu.min.js' %}"></script>
    
    <!-- Morris Charts JavaScript -->
    <script src="{% static 'dashboard/bower_components/raphael/raphael-min.js' %}"></script>
    <script src="{% static 'dashboard/bower_components/morrisjs/morris.min.js' %}"></script>
    <script src="{% static 'dashboard/js/morris-data.js' %}"></script>
    
    <!-- Custom Theme JavaScript -->
    <script src="{% static 'dashboar/dist/js/sb-admin-2.js' %}"></script>

</html>

{% bootstrap_javascript %}

site/dashboard/templates/images.html
{% extends 'dash_base.html' %}

{% block title %} Dashboard{% endblock %}

{% block body_block %}
<style>
    

a{
 word-wrap:break-word;
}

img{
    max-width: 18%;
    height: auto;
    width: auto;
    display:inline-block;
}

.divinline{
    display: inline;
    padding-left: 2px;
    padding-top: 2px;
    padding-bottom: 2px;
}

</style>

    
    <!--table for each rssurl -->
  
        
        <!-- table head  -->
       <div class="row" style="width:100%;" >
           <div class="col-lg-8" style="width:100%;">
               <div class="panel panel-default" style="width:100%;">
                   <!-- /.panel -->
                   <div class="panel panel-default" style="width:100%;">
                       <div class="panel-heading" style="width:100%;">
                           <i class="fa fa-picture-o fa-fw fa-2x"></i>  <strong>All Images</strong>
                       </div>
                       
                       
                       <!-- /.panel-heading -->
                       <div class="panel-body" style="width:100%;">
                           <div class="row" style="width:100%;">
                               <div class="col-lg-4" style="width:100%;">
                                   <div class="table-responsive" style="width:100%;">
   
   
      
      <!-- table -->
      <div class="tablediv" style="overflow:scroll;height: 2000px;">
          {% for each in images %}
          {% if each.image_url %}
          <div class="divinline" style="display:inline"><a href="{{each.image_url}}"><img src="{{each.image_url}}"></a></div>
          {% endif %}
          {% endfor %}
       </div>
    </div>









{% endblock %}